### ISSUE TITLE
[Enhancement] Add options to keyboard mapping

### ISSUE THREAD

**Issue by mrmatteastwood** [schellingb/dosbox-pure#57] opened 2021-01-03 11:19 UTC
Hello @schellingb, there's still a few options that I wonder whether they could be added to keyboard mapping.

**Custom Keybord Bindings**

- Add option to map on-screen keyboard
- Allow mapping left and right analog stick axes (X+/X-/Y+/Y-)

_The above options are available in other keyboard mapping profiles, e.g., "Generic Keyboard Bindings_

**All other keyboard bindings**

- Add more keys to bind, e.g. Tab

**Comment by schellingb** [comment] 2021-01-03 11:51
Sadly none of these I can accomplish in just the core. These would need both libretro API additions as well as changes in the reference frontend (RetroArch).

> Custom Keybord Bindings
> - Add option to map on-screen keyboard

I was thinking of using the keyboard key "Keyboard Compose" as the key to open the on-screen keyboard. But it would be hard to communicate that to a user so I dropped that idea. Currently (if enabled in the options) it's fixed to L3 in the 'Custom Keyboard Bindings' mode. 

> - Allow mapping left and right analog stick axes (X+/X-/Y+/Y-)

That would be a RetroArch addition. But ideally the axes could also be mapped to mouse movement as well as joystick axes but RetroArch doesn't know about DOS joysticks.

>All other keyboard bindings
> -Add more keys to bind, e.g. Tab

The number of binds for the the device modes that aren't custom keyboard are limited to exactly 24 (actually 16 buttons + 4 axes) bind options. So I can't add more options, only change existing ones. The generic keyboard bindings are meant for games that either are fairly simple (think Crystal Caves) or games that have configurable controls.

--------------------

Interestingly everything becomes possible when using the keyb2joypad based automappings. So maybe instead of perusing (or abusing) more possibilities through the frontend, a way to add new or modify existing automappings would be the best. Maaaaaybe something like the start menu as a mapping editor? One could freely assign mouse and joystick movement to sticks and have all key, mouse and joystick buttons selectable. Or a way to define a mapping in a text file or some other intermediate way maybe. I am open to suggestions.

**Comment by mrmatteastwood** [comment] 2021-01-03 13:22
Hmm, regarding adding more keys to bind (e.g. Tab), you mention that it's only possible to bind 16 buttons + 4 axes per stick, totalling 24. That's cool, too, I was just wondering whether it's possible to map different _keyboard keys_ to those _24 buttons/axes_?

The start menu could be a really good alternative, yes! I can totally imagine key/mouse/joystick to button binding as an extra option in that menu. Only thing is, that would then make the key binding options in RA's "Controls" menu redundant, but if they come at least partly from RA, then they'd still be there, confusing users...

**Comment by schellingb** [comment] 2021-01-04 03:21
Here's the current generic bindings:


| BUTTON   | Port 1     | Port 2   | Port 3 | Port 4        |
|----------|------------|----------|--------|---------------|
| UP       | Up         | 8        |   Q    | Backspace     |
| DOWN     | Down       | 2        |   A    | Backslash     |
| LEFT     | Left       | 4        |   Z    | Semicolon     |
| RIGHT    | Right      | 6        |   X    | Quote         |
| SELECT   | Escape     | Period   |   G    | O             |
| START    | Enter      | Enter    |   H    | P             |
| X        | Space      | 5        |   D    | Slash         |
| Y        | Left Shift | 1        |   F    | Right Shift   |
| B        | Left Ctrl  | 0        |   C    | Right Ctrl    |
| A        | Left Alt   | 3        |   S    | Right Alt     |
| L        | 1          | 7        |   W    | Left Bracket  |
| R        | 2          | 9        |   E    | Right Bracket |
| L2       | 3          | Minus    |   R    | Comma         |
| R2       | 4          | Plus     |   T    | Period        |
| L3       | F1         | Divide   |   V    | Minus         |
| R3       | F2         | Multiply |   B    | Equals        |

| AXIS    | Port 1      |  Port 2           | Port 3 | Port 4                |
|---------|-------------|-------------------|--------|-----------------------|
| Left X  | Left/Right  |  4/6              |  Z/X   |  Semicolon/Quote      |
| Left Y  | Up/Down     |  8/2              |  Q/A   |  Backspace/Backslash  |
| Right X | Home/End    |  Minus/Plus       |  J/L   |  Left/Right Bracket   |
| Right Y | PgUp/PgDn   |  Divide/Multiply  |  I/K   |  Minus/Equals         |

These are also used for other device modes if the option `Input > Bind Unused Buttons` is enabled (enabled by default). For those the assignments will shift down depending on the modes default mappings. For example, in 'Mouse with Right Analog' the `X` button is used for the middle mouse button so the `Space` key now goes to `Y` instead.

It's not great, and was made well before I even knew about keyb2joypad, but it was the best I could come up with for the first release. The only "solution" would be to add a core option for every of these with hundreds of choices but I want to keep the amount of options low and control settings should stay in the controls menu of RetroArch as much as possible.

Moving the configuration inside a custom UI into the core is also not perfect but I feel with the automapping we're already halfway there at doing things very DOS specific for a better overall user experience.

**Comment by mrmatteastwood** [comment] 2021-01-04 08:14
Tell ya the truth, shortly after you released the first Beta of Pure, I looked into your generic bindings and I'm now using them as default. I think they're really good.

I used to have my own custom bindings when I was using DOSBox-Core (you can check them out in my screenshots [here](https://github.com/schellingb/dosbox-pure/issues/14#issuecomment-750897055)), and yours are honestly better, not least because you mapped the stick axes as well, which DOSBox-Core can't do.

So from my end, I think being able to map keys different from those you chose for "generic" isn't so important, it's a "nice-to-have" but if it's a lot of trouble and/or causes a ton of redundancy, I don't think it's worth it. Certainly cramming them all into the core options doesn't make sense, I agree.

_(btw, perhaps those tables you posted above should go into the eventual DOSBox Pure guide doc for Libretro Docs (#50)?)_

Re. offering mapping options in a custom UI inside the core: I see it the same way you do. I'm just thinking we need a way to delineate the core's own mapping options from the Controls settings in RA, i.e. set them apart in a way that users will intuitively understand: "oh, this is where I do this and this is where I do that".

I'll rack my brain about this and let you know if I come up with anything.

**Comment by schellingb** [comment] 2021-01-04 08:26
Oh, cool that generic bindings work so well for you. It just seems so awkward that if only a single important key isn't available it's pretty much useless. Well, guess the on-screen-keyboard can help if it's not needed in very hectic gameplay situations.

I found the on-screen-keyboard to be somewhat usable for switching weapons in DOOM, but that is another issue that needs some thought. I was thinking of a customizable next/previous button that cycles through a given list of keys.

Yeah I want to approach the custom UI as a way to modify/tweak the automatic mappings in the first place. But it would also end up allowing tweaks to generic bindings for games than don't have automatic mappings.
And someone on reddit asked how to play Master of Orion which wants mouse movement but also a few specific hostkeys which just aren't covered in the generic bindings. That would become possible as well.

Btw. speaking of, sorry that I haven't replied to #50 yet, quite a few things that are fairly different from DOSBox-SVN... I'm very happy about you helping out in that regard for sure!!

**Comment by mrmatteastwood** [comment] 2021-01-04 09:02
No worries man, one step at a time. I understand and appreciate we're all doing this in our free time :-)

Hey, perhaps you can just bring over the original DOSBox key mapper (cf. [this video](https://www.youtube.com/watch?v=0nVjB9hSoJI))? It can do everything except map mouse movement/buttons, which, perhaps, is something you could add to it. And perhaps it's also possible to add the key cycling functionality you mentioned for DOOM-likes.

As you envisioned, it would then appear as an extra option in the DOSBox Pure start menu: we might call it "Remap game controls". That way, a user would (I guess/hope :-)) understand that from here, they can remap controls specifically for this one game they're about to run.

Then, we'd just need to add a small section about it to the readme explaining that this is specifically for games that need controls that can't be adjusted in the RA Controls menu.

**Comment by OrsV** [comment] 2021-02-10 11:13
Hm, I might have created a duplicate for this with #113 if so we could just mark that as such. Not sure how easy it would be to bring that into RetroArch (load a *.map file from game's root if there) but it's something that is already in the standalone DosBox so at least it's not reinventing the wheel, it also allows for key combinations so it could extend the 24 button limit for specific games that need more as well?

**Comment by thehype1234** [comment] 2021-02-14 00:13
Why not try it the other way round? You have mapped L3 to the virtual keyboard... maybe it is possible to map other buttons to activate the keyboard and also triggers a button press on this virtual keyboard?! Something like a batch file for the keyboard... Sorry if this is stupid. I have no clue on developement, but I’m also looking for a way to map let’s say „x“ under „mouse with right analoge stick.

if this is not possible, is there maybe a way to add known games to keyb2joypad? So that we can map the buttons there? 

Great work mate!

**Comment by demodanza** [comment] 2021-05-16 05:06
Another option could be how Amiga PUAE core has input mapping options for each retropad button inside the core options menu.

![Screenshot_2021-05-16-23-59-14-131_com retroarch](https://user-images.githubusercontent.com/47835860/118386095-d4103380-b5e2-11eb-9aa5-48883a79a43d.png)
![Screenshot_2021-05-16-23-59-42-987_com retroarch](https://user-images.githubusercontent.com/47835860/118386102-de323200-b5e2-11eb-99f3-9f689d267ffe.png)

**Comment by schellingb** [comment] 2022-04-05 19:38
I just committed a new big feature, a built-in full gamepad mapper.

![image](https://user-images.githubusercontent.com/14200249/161833873-781522fa-e5ac-49bf-8fab-882cca66dce0.png)

It's not the most beautiful menu but functionality wise I think it's pretty sweet. Allows any mixture of keyboard, mouse and joystick to be bound to every part of the RetroPad. The mapping is stored inside the savegame data.

This should help with this issue as well as a few others:
- #54 
- #142 
- #179
- #185
- #219
- #232

**Comment by mrmatteastwood** [comment] 2022-04-07 09:18
This looks awesome!!

**Comment by chinagreenelvis** [comment] 2022-04-18 07:20
Very cool. Will this also allow remaps to key combinations?

**Comment by schellingb** [comment] 2022-04-18 08:43
Yes and yes. The mapper is opened via the on-screen-keyboard and available any time and changes are immediately saved and applied when closing the mapper (even the controls menu in RetroArch updates). As of now, it isn't available if the on-screen-keyboard is disabled.

As shown in the screenshot there is a "[Additional Binding]" option which allows the creation of up to 4 bindings per key/axis. Anything can be mapped and combined to anything. For example it is possible to make moving the right analog stick down press a keyboard key, click the mouse and move the joystick and mouse in any direction at the same time. So it should be way more useful and flexible than anything that is possible with just the frontend while avoiding a need to add hundreds of core options.

**Comment by chinagreenelvis** [comment] 2022-04-18 09:15
Fantastic, I look forward to this. DOSBox Pure is revolutionary; I picked a really good time to start getting back into DOS gaming. Thanks for this and keep up the extraordinary work.

**Comment by schellingb** [comment] 2022-04-19 16:00
This new gamepad mapper tool is now out as part of the freshly [released 0.9.0 beta](../releases/tag/0.9.0)!

Please try it out, any feedback would be welcome.

**Comment by gingerbeardman** [comment] 2022-04-19 18:45
I am running macOS so will need to wait to try this, I think?

**Comment by chinagreenelvis** [comment] 2022-04-20 12:08
I will give this a spin as well. I suppose I can figure it out by using it, but I was just wondering if the remapper contains the option to use buttons to speed up/slow down the mouse as well. It's useful in some games so having the option to retain that functionality would be preferable.

**Comment by williambroad** [comment] 2022-04-20 14:57
You, Sir, are genius!! Works like a charme. Completely solved the remapping (turning/strafing) problem in DOS games like Lands of Lore. I cannot begin to imagine all the other possibilities that open up with your mapper addition. Thanks again so much for all the effort you put into that wonderful core.

**Comment by schellingb** [comment] 2022-04-21 13:19
@chinagreenelvis Yes, there is two actions "Speed Up" and "Slow Down" under the "Mouse" device in the Gamepad Mapper that can be bound to anything you want. Though if bound to an analog axis it won't gradually speed up or slow down the mouse, it still is just 3 fixed speed settings.

**Comment by mrmatteastwood** [comment] 2022-04-22 15:39
I had a moment today to take a quick glance at the new mapper. Damn it's sweet. I didn't get to spend much time with it, but one thing I'd like is to be able to quickly cycle up and down through options (e.g. through all the keys available when selecting to map a keyboard) by holding the d-pad or analogue stick up or down. Right now, when I hold the d-pad/stick up or down, the selection only moves one spot, then stops.

**Comment by Denshadego** [comment] 2022-04-24 14:56
Awesome feature! Did some testing, you can even play MS flight simulator on a tablet now!

It seems that when setting new keys to L and R they actually map to the L2 and R2 buttons, and L2/R2 map to L/R buttons, at least when testing on android.

I also second @mrmatteastwood, being able to scroll down/up by holding the button would be nice, both in the pad mapper and the start menu for the core, as having to scroll for the executable file by file in a big directory to start a game is a bit annoying.

That aside, I'm super happy with the core! Thank you for your work!

**Comment by iconoclusterdotexe** [comment] 2022-04-25 08:34
Cannot map Mouse Left Click on Pad Mapper menu. I think the issue is connected here:
![1650875540684](https://user-images.githubusercontent.com/75033413/165051400-2791f479-f702-4e23-95a1-d34eb96792dd.jpg)

There are two Mouse Right Click in `Quick Menu/Controls/Port 1 Controls` menu

**Comment by schellingb** [comment] 2022-04-25 18:33
Thanks everyone for the feedback so far!
I implemented the suggestions for the next version, so look forward to that.
@mrmatteastwood Scrolling by holding down/up is also in, but in the meantime you can use left/right or L/R to jump 12 rows up/down.

**Comment by mrmatteastwood** [comment] 2022-04-25 18:47
Nice! Thanks!

**Comment by schellingb** [comment] 2022-04-26 18:26
The fixes are now in the new [0.9.1 release](../releases/tag/0.9.1). Get it while it's hot!

**Comment by mrmatteastwood** [comment] 2022-04-27 05:25
Juat fantastic! :-) I'm about to go on vacation for 10 days, so I'll finally have time to tinker with this some more. I'm hoping this'll make MDK playable! I don't know how I put up with those asinine controls back in the 90s, lol.

Hey @schellingb, do you think this is a good moment to finish up that readme and submit it to the RA team for inclusion in the official docs?

https://github.com/schellingb/dosbox-pure/issues/50

With my vacation coming up, I'll be more than happy to work together on that and get it out.

**Comment by ZeroAlvein** [comment] 2022-05-17 19:43
I would wish 2 things exist
Im always pro choice/option

So like some people don't have L/R 3 not even 2 sometimes not even 1
I am fully aware we can set which button opens virtual keyboard yet when you have such limited button choice it's simply not an option
So my ideas for improvements are

1 - Simple option we could choose like "show on screen keyboard" and it would simply close the menu and go back to the game bringing up that virtual keyboard

2 - Ability to set combo keys like press this two keys to show on screen keyboard where we could choose combos like for example select and something

**Comment by ZeroAlvein** [comment] 2022-05-17 23:29
> > 1 - Simple option we could choose like "show on screen keyboard" and it would simply close the menu and go back to the game bringing up that virtual keyboard
> > 2 - Ability to set combo keys like press this two keys to show on screen keyboard where we could choose combos like for example select and something
> 
> It's unfortunate that RetroArch was clearly not designed with combination buttons in mind. You might be able to do what you want on your gamepad by setting the "hotkey enable" option, though.
> 
> For example, few games rely on button combinations that involve the back/select button, and no game that I know of relies on using the select button in combination with a d-pad direction. So you could set that button as your hotkey-enabler and then d-pad up to open the menu and d-pad down to bring up the virtual keyboard. These are button combos you'll never accidentally hit since they require hitting the select button with your right hand and the d-pad with your left.
> 
> That being said, DOS games often use so many different keyboard keys that I can't imagine playing on anything less than my 360 controller, and even that gets tricky. But I hope the aforementioned suggestions are helpful.

I don't need a fix that was just a suggestion since i sit in retroarch discord and ppl come there with dosbox configuration problems where most common one is getting controls to work properly
But i gonna suggest them your solution instead of my one which is switching device input to custom keyboard and mouse and simply configuring everything from scratch

**Comment by chinagreenelvis** [comment] 2022-05-17 23:48
Anyone who is dedicated to using a controller that has no thumbsticks and/or r/l buttons/triggers would probably have to resort to using a hotkey-enable button if they aren't sitting next to a keyboard.

Again, in terms of DOS gaming, that sounds silly to me, but a lot of the things I want or prefer probably sound silly to others. So again, hopefully that setup suggestion helps.

**Comment by ZeroAlvein** [comment] 2022-05-18 06:54
> Anyone who is dedicated to using a controller that has no thumbsticks and/or r/l buttons/triggers would probably have to resort to using a hotkey-enable button if they aren't sitting next to a keyboard.
> 
> Again, in terms of DOS gaming, that sounds silly to me, but a lot of the things I want or prefer probably sound silly to others. So again, hopefully that setup suggestion helps.

In short of it i have job i can afford to simply buy another controller
But some ppl are poor or don't have money or whatever other factors can take place in their life that prevents them from buying different controller. 
So maybe instead start imagining you are stuck with controller which don't have analog sticks hence L/R 3 and can't afford to buy different one
And then we can talk about what sounds silly to you

And if you think im exaggerating then this is example just from yesterday about guy who had connectivity issues which caused his controller to switch ports hence not working properly 
![aaaaaaa](https://user-images.githubusercontent.com/99673761/168975902-7747ef01-3e49-4582-967f-4e9452fd21d4.png)

**Comment by chinagreenelvis** [comment] 2022-05-18 12:44
> In short of it i have job i can afford to simply buy another controller But some ppl are poor or don't have money or whatever other factors can take place in their life that prevents them from buying different controller. 

Bro what

> So maybe instead start imagining you are stuck with controller which don't have analog sticks hence L/R 3 and can't afford to buy different one

I literally just did and offered you the only available solution there is

> And then we can talk about what sounds silly to you

And I followed up the comment in all humility by saying that the things I want often sound silly to others. I'm offering the best help I can, so I'm sorry if my commentary about the best solution being having a controller with more buttons is literally the best one. At least my response wasn't just "Get a better controller,"

It really doesn't pay to ever say anything on the Internet these days. Consider my participation here limited to interacting directly with the author from now on. Sheesh.

**Comment by schellingb** [comment] 2022-05-18 14:06
@ZeroAlvein I told you in #260 that you were rude and instead of finding a better way to express yourself now you're an asshole towards others here? Consider this your last warning. Your suggestions for improvements are as welcome as anyone's but you need to work on the way you phrase things or you'll find yourself banned in many communities.

@chinagreenelvis Truly sorry about that! Glad to see you stick around, feel free to ignore anyone, your input and feedback is most welcome to me.

**Comment by chinagreenelvis** [comment] 2022-05-18 14:15
Oddly enough, it's usually me who is the asshole getting banned.

Nobody needs to apologize for anything, I totally understand Zero's position and the complicated nature of setting things up through RetroArch. Still, it's not my place to step in and offer help in someone else's github, let alone to respond (and in the process contribute) to drama.

**Comment by schellingb** [comment] 2022-05-18 16:18
Good, so we can go back to being productive here.

**Comment by Stellan90** [comment] 2022-05-23 10:31
Hi, A alredy great DOS emulator made even better with this gamepad mapper!
The only feature that i miss is to remap the second controller in a similar way as the first controller.

There is a game that me and my brother played as kids and would love to play again preferably on the big screen with controllers. The game in question is "Liero" but the problem is that to be able to dig through dirt you have to hold the direction you want to move and then tap the opposite direction to dig forward. This isn't a problem with a keybord but with a d-pad it's impossible. So what I have done with the first controller is to map a "dig" button which in turn presses left and right at the same time.
I can't find a way to do this for the second controller and I would very much appreciate any help with this problem.

**Comment by schellingb** [comment] 2022-05-23 10:44
Hehe, I agree that would be great.

The gamepad mapper builds on top of the automatic keyboard mappings which I implemented in a fixed way so it only is available for the first controller. Also only the first controller gets a button to open the on-screen-keyboard, so this makes things even trickier. Maybe the mapper would still be operated by the first controller but would have a switch to set for which controller the mapping is edited. I need to think about this.

If it's a pure keyboard game you can go into the `Quick Menu` in RetroArch, then `Controls` -> `Port 2 Controls` and set `Device Type` to "Generic Keyboard Bindings". This should allow the customization you want. You can then click `Save Game Remap File` to make the customized controls specific for that one game, too.

And thanks for the feedback!

**Comment by Stellan90** [comment] 2022-05-23 11:19
> Hehe, I agree that would be great.
> 
> The gamepad mapper builds on top of the automatic keyboard mappings which I implemented in a fixed way so it only is available for the first controller. Also only the first controller gets a button to open the on-screen-keyboard, so this makes things even trickier. Maybe the mapper would still be operated by the first controller but would have a switch to set for which controller the mapping is edited. I need to think about this.
> 
> If it's a pure keyboard game you can go into the `Quick Menu` in RetroArch, then `Controls` -> `Port 2 Controls` and set `Device Type` to "Generic Keyboard Bindings". This should allow the customization you want. You can then click `Save Game Remap File` to make the customized controls specific for that one game, too.
> 
> And thanks for the feedback!

Thanks for the answer. Yes I think that the mapper would only be operated by the first controller with a switch just as you suggest.

I can't get the "Generic Keyboard Binding" option to work either, because the function I need is for example the "A" button to press the "A" and "D" keys on the keyboard at he same time, just as I did with te first controller that presses the "Left" and "Right" keyboard keys at the same time.

**Comment by schellingb** [comment] 2022-05-23 11:22
Ah, sorry about that, now I get it. Yeah, as you said, double-mappings like that is exclusive to the mapper. I'll see what I can do :-)

**Comment by schellingb** [comment] 2022-06-05 15:30
I'm thinking of doing a small change that might cause annoyance for some...

Currently the default "Device Type" for "Controller Port 1" is "Gravis GamePad (1 D-Pad, 4 Buttons)". I'm thinking of swapping that with "Generic Key Bindings". Of course if the game is detected with an automatic gamepad mapping that will continue to be the default.

Having something that acts as a DOS joystick active will confuse some games. A really bad case is Tomb Raider which is unplayable while a DOS Joystick exists because it has no calibration for joysticks and it sees the joystick always holding a bit to the left making the main menu unusable. As reported in #265.

Ideally the behavior of the joystick emulation would be improved so it looks more like a real joystick but it is rather complex. As far as I understand the emulation is faking an electrical signal of some sorts so it might need more research than just tweaking a number...

**Comment by nl255** [comment] 2022-08-12 12:14
So this would work well for Arena since melee attacks are done by moving the mouse while holding down the right mouse button (i.e. map a button to move mouse left, then right all while holding down the mouse button)?  Also, does this require the use of .dosz files or will it work if you run a .bat file from the retroarch menu (or emulationstation menu) that mounts the game folder and then runs the game executable?

**Comment by jeff93063** [comment] 2022-08-17 15:18
> I found the on-screen-keyboard to be somewhat usable for switching weapons in DOOM, but that is another issue that needs some thought. I was thinking of a customizable next/previous button that cycles through a given list of keys.

Is this possible with the new mapper? I wasn't able to find it. It would really help in Terminal Velocity, where there are a bunch of weapons and the only way to select them is with the number keys. 

Thanks

**Comment by schellingb** [comment] 2022-08-19 16:52
@nl255 The gamepad mapper works regardless of how the content is loaded. Can be a ZIP file, a CD image like .ISO, can be a local EXE/COM/BAT file (which mounts the folder that is in) or a .CONF file. For the options that mount a directory from the local filesystem it will create a file `PADMAP.DBP` in that directory. For the other options that file is stored into the save file for that game.

@jeff93063 Currently the gamepad mapper can bind multiple keys to a single button but then pressing that button presses all the keys at the same time. Having an option to bind multiple keys and then have the button toggle through them seems a cool idea. Though if you map 1 to 7 for the weapons in DOOM, as long as you don't have picked up all weapons, toggling through will sometimes just do nothing and the user might not be sure what key they're on currently...

**Comment by jeff93063** [comment] 2022-08-19 16:59
Yes, I thought that might be an issue. Another idea is to allow assigning the numbers to directions on an analog stick. For example, moving straight up (12:00 position) would give you "1", diagonal up/right would be "2", etc. Kind of like some modern games that use a "weapon wheel", like far cry 4. What do you think?

**Comment by schellingb** [comment] 2022-08-19 17:12
That's a cool idea, too! Ideally the core would draw some wheel onto the screen then while engaging with the analog stick. I really like that but it won't be easy to implement... I do like it very much though :-)

**Comment by jeff93063** [comment] 2022-08-19 17:16
Awesome, the on-screen wheel would make it even better. Come to think of it, it would solve the issue with the previous idea (increment/decrement weapon number) if you could display the number for a second in an overlay. That way you'll always know what number you're on.

**Comment by schellingb** [comment] 2022-08-19 17:27
Oh yeah, maybe to make things a bit simpler implementation wise (and also for the menu needed to configure this whole thing) maybe having a toggle option that just displays the key name on screen somewhere would be much easier. Won't be as cool as a wheel could be but it might be more realistic scope wise :-)

**Comment by nl255** [comment] 2022-08-19 23:35
@schellingb Looks like it doesn't work with TES: Arena since I mapped a button to left mouse button + move mouse right + move mouse left and it didn't work (what I was trying to do is have the mouse move right, then back left while holding down the left mouse button).  Though it might be a more general issue since even doing it manually with the right analog stick mapped to mouse movement and l1/r1 mapped to the left/right mouse button either.

**Comment by chinagreenelvis** [comment] 2022-08-21 21:57
[ArenaPadmap.zip](https://github.com/schellingb/dosbox-pure/files/9390009/ArenaPadmap.zip)

In order to get the attacks to work with a controller in Arena, you have to make button combos that also speed up the mouse. Attached is my own PADMAP.DBP file which you can drop into the Arena.pure.zip file in the RetroArch saves folder.

**Comment by zardozerr** [comment] 2022-10-09 20:03
The keyboard mapper works great for many things, but can it map a keyboard key to a different keyboard key? Maybe it's possible and I'm missing something. It would be great for some games that don't use WASD because they came before it was standard. I'm thinking of Eye of the Beholder, where you have to use the arrow keys or the numpad to move.
A suggestion, when bringing up the on-screen keyboard, is to have a rebinding menu when you right-click on a key. If there's already another way to rebind a key to another key (without using a third-party rebinding app), please let me know!

**Comment by Kupo91** [comment] 2023-12-16 16:11
Hi, I was wondering why there is no option to emulate the mouse wheel. It seems there is such a setting in the core options, but I think it's only for DOS games? 
I'm emulating Windows 98 and some games use the mouse wheel to zoom in/zoom out. So I would love to put Scroll Up/Scroll Down on let's say L2 and R2, but I can't find an option for this in the Gamepad Mapper.

**Comment by schellingb** [comment] 2024-12-29 18:34
I'll close this issue now. Nowadays keyboard mapping has many more options. In the frontend a controller port can be set to one of these keyboard related options:
- Generic Keyboard
- Custom Keyboard Bindings
- Custom Keyboard + Mouse on Left Stick and B/A/X
- Custom Keyboard + Mouse on Right Stick and L/R/X
- Pad Mapper

When using one of the "Custom Keyboard" device, all buttons can be mapped to keyboard keys in the frontend. On the other hand when using the "Pad Mapper" device the buttons can be freely mapped with the in-core Gamepad Mapper which is accessible from the Start Menu or the On-Screen Keyboard. The Gamepad Mapper allows free binding of all buttons to any DOS device (keyboard, mouse, joystick) and in the newest version of the core [1.0-preview1](../releases/tag/1.0-preview1) (available here and from the RetroArch online core downloader) it has two new features "Action Wheel" and "Shift Gamepad Mapping While Holding a Button" which offer additional control customization.

**Closed by schellingb** 2024-12-29 18:34 UTC
Labels: enhancement
