### ISSUE TITLE
Can't Install Dosbox Pure core in Retroarch on Android 4.4 on GPD XD?

### ISSUE THREAD

**Issue by ThorpadoLegend** [schellingb/dosbox-pure#116] opened 2021-02-12 12:49 UTC
Hi, I wanted to install the core on my 32 bit Retroarch on Android 4.4 on my GPD XD but cannot get it working?

**Comment by schellingb** [comment] 2021-02-12 14:03
Duplicate of #112.
It seems like the libretro buildbot runs a version of Android SDK/NDK that is too new for cores that use pthread to be usable on Android 4.4. I don't know how to solve this at this point.

**Closed by schellingb** 2021-02-12 14:03 UTC
