### ISSUE TITLE
No external framerate/variable refresh support.

### ISSUE THREAD

**Issue by n1ghttrap** [schellingb/dosbox-pure#4] opened 2020-12-22 00:45 UTC
Pretty obvious in any game that runs at 70hz, which is most of them in DOS.  Frame pacing is quite bad.  Would be nice to have the 'external' framerate option the main DOSbox core has.

**Comment by schellingb** [comment] 2020-12-22 02:44
I was worried about this :-)  
It didn't strike me as an issue, but I'm not that sensitive to it.  
I absolutely don't want something akin to the timing mode option in the other DOSBox cores. What is a user supposed to do with this description
```
      Internal mode works on an internal scheduler. DOSBox will render frames at it's own pace which 
      may result in additional input lag and judder. Cycles modes "auto" and "max" should work as intended.
      There is a fixed 60 fps mode and a variable framerate mode.
      External mode works based on the frontend's scheduler. It should offer lower input lag but requires a fixed
      cycle rate. It should offer smoother scrolling, and no judder.
```
To me, even as a developer with somewhat of a technical understanding of the problem at hand, this is just gobbledygook.

Sadly the way original DOSBox is architectured, this was the best I could do for now. Maybe me or someone else can look into it how to make the necessary changes to make DOSBox a better fit for a framework like libretro.

**Comment by n1ghttrap** [comment] 2020-12-22 03:00
Whatever it is, external works in the original core, and all standalone versions of it sync to 70hz fine.  Consider it at least, please.  On a VRR monitor it does make a lot of difference.

**Comment by realnc** [comment] 2020-12-22 15:45
> I absolutely don't want something akin to the timing mode option in the other DOSBox cores. What is a user supposed to do with this description
> 
> ```
>       Internal mode works on an internal scheduler. DOSBox will render frames at it's own pace which 
>       may result in additional input lag and judder. Cycles modes "auto" and "max" should work as intended.
>       There is a fixed 60 fps mode and a variable framerate mode.
>       External mode works based on the frontend's scheduler. It should offer lower input lag but requires a fixed
>       cycle rate. It should offer smoother scrolling, and no judder.
> ```

That's the SVN description. In core, I changed it to:

```
External mode is the recommended setting. It enables the frontend to drive frame
pacing. It has no input lag and allows frontend features like DRC and Frame Delay
to work correctly. Internal mode runs out of sync with the frontend. This allows
for 60FPS output when running 70FPS games, but input lag and stutter/judder are
increased. Use only if you absolutely need 60FPS output with no tearing in 70FPS
games. 
```

Note that this is not just for VRR. Doing this is essential for RetroArch to be able to reclock the core to the user's display refresh rate when playing 60Hz games on non-VRR displays. A 60.2Hz game for example will have periodic stutter on a normal 59.94Hz monitor. However, RetroArch will run the core at a slightly different speed (from 60.2 to 59.94 in this example) to prevent the stutters.

The changes required for this are rather simple. You can grep the dosbox-core sources for `run_synced` to see what's different between the two modes. However, the auto/max cycles adjustment algorithm of dosbox goes apeshit in external timing mode, so you need to use fixed cycles only.

**Comment by schellingb** [comment] 2020-12-22 16:07
I see, Core also only has 2 option as opposed to the 3 in svn.

Still, none of the option seem great. Maybe the cycle count could be calculated on boot? Not sure seeing as max cycles seems widely different in protected and non-protected mode.

@realnc Have you ever thought about taking apart the DOSBox main loop and implementing it more correctly (i.e. without threads or coroutines or any shenanigans)? Seeing as DOSBox uses the native call stack as a DOS process stack it seems a bit daunting. I'm wondering how big of a change to DOSBox it really would be...

**Comment by realnc** [comment] 2020-12-22 16:47
> Have you ever thought about taking apart the DOSBox main loop and implementing it more correctly (i.e. without threads or coroutines or any shenanigans)? Seeing as DOSBox uses the native call stack as a DOS process stack it seems a bit daunting. I'm wondering how big of a change to DOSBox it really would be...

The actual emulation loop is event-driven and it would be easy to integrate it in the `retro_run()` main loop. See `LoopHandler` and `DOSBOX_RunMachine() in `include/dosbox.h`. But the shell is used as the application main loop in dosbox, and that one looks like a nightmare to convert into something event-driven :-/

**Comment by schellingb** [comment] 2021-01-06 18:09
In the latest release I tweaked a bit how the frame refresh is submitted to RetroArch.
@n1ghttrap If you can, try it out please and report if things feel better, worse, or about the same. Thanks.

**Comment by n1ghttrap** [comment] 2021-01-06 19:38
It's definitely improved, but what I see happening is that the core updates at the selected refresh rate.  So it runs at 120hz if I run at a 120hz mode, and it squeezes all the frames the core actually renders within that limit.  At least when strafing in Wolfenstein this seems smooth enough.  However, sending the exact amount of frames as the display mode refresh rate means vsync instead of gsync/freesync takes over and adds a tad of latency, and while I haven't measured it, it feels a tad laggier with vsync on instead of off.  The behavior in the original dosbox core with external timing is that it will send the exact amount of frames the game is rendering to the GPU.  So you'll get 70 a lot of the time, instead whatever the display mode is set to (like 120 in my case), which allows VRR to work more effectively.

**Comment by schellingb** [comment] 2021-01-06 19:57
Thanks for testing. You described the current intended behavior.
I'm close to biting the bullet and adding the option for the external timing. You're giving good reasons :-)
Or maybe instead of an option, it could just be the default when cycles are specified manually. Because as @realnc explained the external timing mode won't work with auto/max cycles mode.

**Comment by n1ghttrap** [comment] 2021-01-11 22:59
Yeah just let me know when you have it implemented, and how to utilize it.  I'll test it at that point.

**Comment by realnc** [comment] 2021-01-12 04:44
> Or maybe instead of an option, it could just be the default when cycles are specified manually. Because as @realnc explained the external timing mode won't work with auto/max cycles mode.

Often, people want fixed cycles with internal mode. This is usually the case for people who use 60Hz display to play 70Hz DOS games. In external mode, RA will disable vsync in order to be able show 70FPS on 60Hz. In internal mode, 60Hz is reported to RA even for 70Hz games and the core ends up just not sending some of the frames to RA.

**Comment by schellingb** [comment] 2022-06-02 15:23
As of version 0.21 which was released late last year there is now the core option `Emulation Options` > `Force 60 FPS Output` which should help to run with hardware vsync on many more hardware configurations and devices. Further feedback please post in #184 as the whole development discussion is contained there. Closing this now.

**Closed by schellingb** 2022-06-02 15:23 UTC
