### ISSUE TITLE
Dosbox Pure is unable to play games from zip files when they are several gb

### ISSUE THREAD

**Issue by triggerthehorizon** [schellingb/dosbox-pure#161] opened 2021-05-16 19:41 UTC
I am unable to play games like Wing Commander IV, Pandora Directive and Ripper. If the game is unzipped, it plays fine. As soon as I zip the game and change the extension to .dosz, Dosbox Pure says No Executable File Found. The correlation is that these games weight about 3 gigs each. I think Dosbox Pure is running into issues when the zips are too large.

**Comment by PoloniumRain** [comment] 2021-05-17 02:40
I have these games so i just tried The Pandora Directive and can confirm that it doesn't work once it has been zipped. However, this same issue has been reported before #15 and it looks like @schellingb fixed it ages ago... But somehow it's back again...

For example, The Pandora Directive is 3.57GB when zipped and at this size it wont work, but if i delete three of the .ISO files, reducing the zip size to 1.78GB, then it will now work correctly. When a zip file goes over 2GB i just get "No executable file found". So it looks like issue #15 has returned.

Tested with DBP 0.13 and Retro Arch 1.9.2.

**Comment by schellingb** [comment] 2021-05-17 03:11
Can you open these .ZIP files in 7zip and press the "Info" button on the toolbar and see if it lists fields like `Characteristics: Zip64` or `64-bit`? As written in that issue #15 we don't support Zip64 and ZIP files which exceed 4GB uncompressed only work as Zip64 (smaller ZIPs can also be Zip64 but I think all tools out there avoid Zip64 if possible to increase compatibility).

**Comment by PoloniumRain** [comment] 2021-05-17 04:14
@schellingb 7zip reports it as a standard zip...

![info](https://user-images.githubusercontent.com/50634894/118430134-465c4300-b6cb-11eb-8957-4f997bac338e.jpg)

I've discovered that the problem is with DBP 0.13, because 0.12 and 0.11 both work. It's exactly as mentioned in issue #15 where it has to do with 2GB zipped files. 

To test this i created a zip that is exactly 2.06GB, and uncompressed it is 2.35GB.
With DBP 0.13: The zip file will not work, i just get "No executable file found" on the Start Menu screen. 
With DBP 0.12 and 0.11: The zip file works and i can view all the files on the Start Menu and the game runs fine.
If i then reduce the zip file to just under 2GB (1.97GB) it will now work fine with 0.13. So the problem is with 0.13.

I tested these DBP versions with:
Window 10
RA 1.9.0
RA 1.9.2
Latest RA nightly

Here's another example with the game 'The Pandora Directive' which is 3.57GB...

![versions](https://user-images.githubusercontent.com/50634894/118431503-6e997100-b6ce-11eb-8d58-07a01b7ce140.png)

**Comment by schellingb** [comment] 2021-05-17 09:41
Unable to confirm this here. ZIPs between 3 and 4 GB work fine for me on 0.13 on both Windows 10 (64-bit and 32-bit) and Linux (64-bit). On Linux ARM 32-bit it does not work, but I don't think it ever has (not new to 0.13). I can fix 32-bit Linux.

**Comment by triggerthehorizon** [comment] 2021-05-17 10:14
Forgot to mention I am using Windows 10 64 bit and Retroarch 1.93 with latest Dosbox Pure core.
What tool should I use to compress these games to get them to work? Right now I am using 7zip to save as a .zip file

**Comment by schellingb** [comment] 2021-05-17 11:23
7zip if fine.
I ended up trying a bunch of ZIPs on a different machine and ended up finding an issue in the ZIP file indexing. It's not actually related to the file size, but on number of and naming of the contained files. The fix will be in next release. Thanks for reporting this!

**Comment by triggerthehorizon** [comment] 2021-05-17 11:43
Thank YOU for making such a great core :)

**Comment by PoloniumRain** [comment] 2021-05-17 12:21
@schellingb Ah glad you found it! :)

BTW, from my understanding, even with your fix any zip over 4GB will still not work because of no Zip64 support? Because @triggerthehorizon mentioned Ripper, and that game is 4.15GB when compressed and 4.24GB uncompressed.

Just so you know, these look like the only DOS games that are over 4GB:
Ripper
Phantasmagoria (I have a 2GB version of this game, but there's a 5GB+ version. Don't know how it's different)
Phantasmagoria 2
Links LS
Gabriel Knight 2

**Comment by schellingb** [comment] 2021-08-29 19:15
Now released in 0.16 which is available on the releases of this GitHub project and should appear in the core downloader in the next 24 hours (I think).

**Comment by schellingb** [comment] 2021-09-12 18:06
> Just so you know, these look like the only DOS games that are over 4GB:
> Ripper
> Phantasmagoria (I have a 2GB version of this game, but there's a 5GB+ version. Don't know how it's different)
> Phantasmagoria 2
> Links LS
> Gabriel Knight 2

@PoloniumRain If you have some of these large games, can you try them with 0.16 or newer and see if they load now directly from ZIP?

**Comment by PoloniumRain** [comment] 2021-09-12 21:40
> > Ripper
> > Phantasmagoria
> > Phantasmagoria 2
> > Links LS
> > Gabriel Knight 2
> 
> @PoloniumRain If you have some of these large games, can you try them with 0.16 or newer and see if they load now directly from ZIP?

Just tried all of those games and they each load fine from ZIP with 0.16. All of the game files are visible on the Start Menu as well. I tested on Windows 10 with RA 1.99. 

So those should be all of the DOS games that are over 4GB. I also played for a few minutes each on Gabriel Knight 2, Links LS and Phantasmagoria 1/2 and didn't encounter any issues, everything works great :)

**Closed** 2021-10-18 18:25 UTC
