### ISSUE TITLE
Keyboard key remapping via *.map files

### ISSUE THREAD

**Issue by OrsV** [schellingb/dosbox-pure#113] opened 2021-02-09 18:03 UTC
Hi,

I saw this isn't exposed/supported like in the standalone DosBox. Is there already a way to do this in RetroArch directly (tried to do it with game config overrides, but no luck, it just ignores my settings)? If not is this a technical limitation? While most dos games support changing keyboard keys, some don't so this would be nice to have.

A core setting (on/off) to make it look for DosBoxKey.map in the root of the game/zip would do and could be later extended to be linked from the config files when/if they become functional.

This would also benefit GamePad users since you could sacrifice a key (left trigger for example) to be used as a modifier key which would give you (n-1)*2 keys available in the game where n is the number of buttons available on the GamePad. 

Thanks.

**Comment by schellingb** [comment] 2021-02-13 18:14
We already have the controls customization through libretro (as exposed in the Controls menu in the RetroArch quick menu) as well as the automapping system that identifies games and applies controls based on the keyb2joypad project. I'm aware that it is not enough as is but I'm not sure how to either expand one of these two systems or what a third system would be.

It's not a simple thing to get support for the original DOSBox mapper into this core as that relies heavily on the SDL parts that have been thoroughly removed in favor of libretro in this core. Re-implementing map file support would mean to go through a similar approach of what the automapping currently does. But even that, in it's current form, does not support the modifier keys you mentioned.

So yeah if the request is "accommodate more usecases" (as opposed to specifically a need for .map file support) this issue could be marked as a duplicate of #57.

**Comment by OrsV** [comment] 2021-02-15 10:48
Thanks for the answer. It doesn't need to be the DOSBox mapper, but I did like how it passed events to the game itself which could be mapped to any physical key or combination. The libretro controls are fine for gamepads (if somewhat limited, not allowing for modifier keys), however I couldn't find a way to remap keyboard keys with it (have "w" behave as "up" in the dosbox-pure core) which I really would like to have somehow (don't mind editing text files as long as it can be achieved and is documented somewhere).

**Comment by ParadoxGBB** [comment] 2021-12-02 23:23
+1 on the RMP documentation part. I'd love to convert my .map files to .RMPs. I'm ok with editing files.

A good example is Pinball Fantasies, the opening screen has a funky interface where you choose F1-F4 to select each table and I had a way of doing it pretty intuitively with a .map. DosBox-Pure is awesome and I'd love a way to get this over to this core. 

Also for whatever reason a large chunk of my DOS games are not autodetected and a few that are don't seem to work correctly, epecially for things like WASD for Doom2 or Wolf3D.

**Comment by schellingb** [comment] 2022-04-19 16:03
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.

**Closed by schellingb** 2022-04-19 16:03 UTC
