### ISSUE TITLE
dlopen failed: cannot locate symbol "__register_atfork"

### ISSUE THREAD

**Issue by dre10g** [schellingb/dosbox-pure#112] opened 2021-02-08 21:33 UTC
GPD XD running Android KitKat Legacy Rom 4.4.4
Loading the core in retroarch it does nothing (like usually it shows the core loaded in the bottom left hand corner - it just says (No Core)

When opening a zip within retroarch this error pops up: ""Failed to open libretro core"

Retroarch logs:

`    === Build =======================================
    Capabilities:  NEON VFPv3 VFPv4
    [INFO] Built: Aug 11 2020
    [INFO] Version: 1.9.0
    [INFO] Git: 6388872
    [INFO] =================================================
    jni_thread_destruct()
    [CORE]: Loading dynamic libretro core from: "/data/data/com.retroarch.ra32/cores/dosbox_pure_libretro_android.so"
    Failed to open libretro core: "/data/data/com.retroarch.ra32/cores/dosbox_pure_libretro_android.so"
    Error(s): dlopen failed: cannot locate symbol "__register_atfork" referenced by "dosbox_pure_libretro_android.so"...
    [Environ]: SET_PIXEL_FORMAT: RGB565.`

**Comment by schellingb** [comment] 2021-02-09 13:40
That is a bummer, it looks like the build made with newer Android build tools is not really compatible with Android 4.4 even though it should be...
Can you post where the versions you are using is from? Both RetroArch and the DOSBox Pure core. From Play Store, buildbot, F-Droid or wherever.

**Comment by dre10g** [comment] 2021-02-09 19:45
Retroarch_ra32.apk (1.9.0) - Git version: 6388872
Dosbox Pure was downloaded through retroarch online updater. Can't really check the version as it won't load the core.. unless there's another way I can check?

**Comment by dre10g** [comment] 2021-02-11 19:46
I just manually installed the latest pure core. But it does the same thing.

**Comment by schellingb** [comment] 2021-02-12 15:52
I was able to reproduce the error locally by running the Android 5.0.2 x86_64 system image in the emulator. The emulator refused to load older system images like 4.4 but the error is the same on Android 5.

I then proceeded to build the core with my local version of the Android NDK (which is version 20) and the resulting core ran fine in the emulator. So as expected the buildbot builds with a new version of the SDK/NDK and Google is a horrible company when it comes to backwards compatibility so the official libretro builds do not run.

I'm attaching my build for armv7 to this post. You can extract the file `dosbox_pure_libretro_android.so` from the ZIP and place it somewhere on the device and then use the function `Main Menu` -> `Load Core` -> `Install or Restore a Core` to manually install it.

Download: [dosbox_pure_libretro_android-armeabi-v7a-0.10-20210213.zip](https://github.com/schellingb/dosbox-pure/files/5972872/dosbox_pure_libretro_android-armeabi-v7a-0.10-20210213.zip)

**Comment by schellingb** [comment] 2021-02-13 14:26
Fixed by 96837ac.
Builds created by the buildbot now run on older Android versions. I tested Android 5.0.2 but this should also apply to 4.4.
@dre10g @ThorpadoLegend If you have some time, please try out the newest version available on the core online updater!

**Comment by dre10g** [comment] 2021-02-13 21:51
You legend! Just tested via online updater and it works.
Thank you. Much appreciated!

**Closed** 2021-02-23 18:15 UTC
