### ISSUE TITLE
Changing the default D drive from the save file to the ISO file

### ISSUE THREAD

**Issue by killer1500nw** [schellingb/dosbox-pure#340] opened 2022-08-29 11:59 UTC
Any chance you can provide an option to change the D drive from the save location to the ISO file for CD ROM games when running an OS? Maybe just make it E?

Alot of early Windows 95 cd games have copy protection that needs to read a game from a drive with the disk label D, I've run in to a few games via emulation and native on my Win95  machines, and in Win10 using compatibility layers such as Dgvoodoo that check to see if a disk is in the D drive (must be D) and quite often check for Redbook audio.  This happens regardless if I use physical (even it its burnt media) or something like Daemon tools.

The reason I know this is because one of HDDS on my PC had a had this label. Once I changed this label a bunch of old games would work. 

One example of this is Earthworm Jim the Win 95 version, this game will only work if the disk drive is D, which doesn't work with Dosbox pure due to it being the save hdd disk having the D label.

**Comment by Vlek** [comment] 2022-09-17 23:30
Attempting to resolve the issue by changing the configuration:

First, I confirmed that I am seeing what you're seeing. I loaded a .zip file in RetroArch using Dosbox Pure as the core. It mapped the zip file's contents as the D: drive and then mounted the CD as the E: drive.

Things I tried that didn't work:
- [Renaming the zip file as per the readme](https://github.com/schellingb/dosbox-pure#mount-zip-as-a-or-d-drive). It even stopped recognizing that there were files in the zip file and did not mount the cd.
  - I tried both upper and lowercase letters for the zip extension and the drive letter.
  - I also tried renaming the zip file to end in .dosz, that caused Windows 98 to exception.
- Loading an ISO directly without using a zip folder. In that case, it mounted an empty disk to the D: drive and mounted the CD as the E: drive.


Things that might work:
- Using the RetroArch CD changer, I am thinking though that this might just change where the E: drive points to, it won't unmount the D: drive.
- Using the `REMOUNT` command in the commandline OR in a batch file. This is the one I am thinking will likely work in the end.


I am curious though why the renaming of the file does not work as the README states. I think that might be a bug.

**Comment by schellingb** [comment] 2022-09-18 18:44
When running an installed operating system like Windows, the operating system is in charge of how it handles drives and at this point DOSBox is purely a low level CPU emulator. Windows 9x is built in a way where drive letters for hard drives always come before drive letters of CD-ROM drives.
So the only way to get the CD-ROM be the D: drive is by having no D: drive. I described one way to do this in an issue that seems very similar to this one: [#308](308#issuecomment-1186194329)

**Comment by killer1500nw** [comment] 2022-09-23 08:24
Oh, that sucks, At least there is a workaround I guess. Maybe look at providing an option to disable the 2nd HDD so the CD Disk drives default to D, similar to the workaround. 

Frustrating as a lot of games from 1995, 1996 and some 97 games require a disk drive letter to be D for some stupid reason.

**Comment by schellingb** [comment] 2024-12-29 18:05
The newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader has a new 'Disable D: Hard Disk (use only CD-ROM)' choice on the "Free Space on D: in OS" core option which should help. I'm closing this issue now because I don't think much more can be done on the core side.

**Closed by schellingb** 2024-12-29 18:05 UTC
